---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/data_bags
  environments_path: test/environments

platforms:
  - name: ubuntu-14.04

suites:
  - name: production
    provisioner:
      client_rb:
        environment: directory-prod
    run_list:
      - recipe[chef_directory::default]
    attributes:
      mysql:
        host: <%= `ipconfig getifaddr en0` %>
        password: directory

  - name: staging
    provisioner:
      client_rb:
        environment: directory-stg
    run_list:
      - recipe[chef_directory::default]
    attributes:
      mysql:
        host: <%= `ipconfig getifaddr en0` %>
        password: directory
      deployment:
        nginx:
          prefix: staging
