---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/data_bags

platforms:
  - name: ubuntu-14.04

suites:
  - name: production
    run_list:
      - recipe[chef_directory::default]
    attributes:
